---
name: security

# Run for all pushes to main and pull requests when Go or YAML files change
on:
  push:
    branches:
      - main
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
  schedule:
    - cron: '23 20 * * 2'

jobs:
  scan-trivy:
    name: sec-scan-trivy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          security-checks: 'vuln,config,secret'
          ignore-unfixed: true
          format: 'table'
          severity: 'HIGH,CRITICAL'
          skip-dirs: 'tests'

